server:
  port: 8080
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false

spring:
  application:
    name: task-manager
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  datasource:
    url: jdbc:${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
  search-engine:
    common:
      log:
        sender: true
      metrics:
        sender: true
      notification:
        sender: true
    task-manager:
      secret: ${SECRET_KEY}

logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO